include ../Makefile.drivers_common

# other values supported are sx1262, sx1268 and llcc68
LORA_DRIVER ?= netdev_default
USEMODULE += $(LORA_DRIVER)

USEMODULE += shell_cmds_default

include $(RIOTBASE)/Makefile.include
